# Data manipulation with Numpy and Pandas

Handling large data in Python is very elegant. In the simplest way you can use plain arrays. However, they are pretty slow. Numpy and Panda are two great libraries for dealing with datasets. Numpy is used for homogenous n-dimensional data (matrices). Pandas is used for heterogenous tables (CSV, MS Excel tables). Pandas is internally based on Numpy. See http://scipy-lectures.github.io/ for a more detailed tutorial.

In [1]:
import numpy as np

In [2]:
# Generating a random array
X = np.random.random((3, 5))  # a 3 x 5 array

print(X)

[[ 0.10753124  0.40756125  0.11140892  0.62782566  0.11652958]
 [ 0.80954456  0.96146941  0.41915297  0.60044991  0.95843071]
 [ 0.98238451  0.52221654  0.75277142  0.9239605   0.16104512]]


### Accessing elements

In [3]:
# get a single element
X[0, 0]

0.10753123537199871

In [4]:
# get a row
X[1]

array([ 0.80954456,  0.96146941,  0.41915297,  0.60044991,  0.95843071])

In [5]:
# get a column
X[:, 1]

array([ 0.40756125,  0.96146941,  0.52221654])

In [6]:
# Transposing an array
X.T

array([[ 0.10753124,  0.80954456,  0.98238451],
       [ 0.40756125,  0.96146941,  0.52221654],
       [ 0.11140892,  0.41915297,  0.75277142],
       [ 0.62782566,  0.60044991,  0.9239605 ],
       [ 0.11652958,  0.95843071,  0.16104512]])

In [7]:
print(X.shape)
print(X.reshape(5, 3)) #change the layout of the matrix

(3, 5)
[[ 0.10753124  0.40756125  0.11140892]
 [ 0.62782566  0.11652958  0.80954456]
 [ 0.96146941  0.41915297  0.60044991]
 [ 0.95843071  0.98238451  0.52221654]
 [ 0.75277142  0.9239605   0.16104512]]


In [8]:
# indexing by an array of integers (fancy indexing)
indices = np.array([3, 1, 0])
print(indices)
X[:, indices]  

[3 1 0]


array([[ 0.62782566,  0.40756125,  0.10753124],
       [ 0.60044991,  0.96146941,  0.80954456],
       [ 0.9239605 ,  0.52221654,  0.98238451]])

### Operations along an axis

In [9]:
X

array([[ 0.10753124,  0.40756125,  0.11140892,  0.62782566,  0.11652958],
       [ 0.80954456,  0.96146941,  0.41915297,  0.60044991,  0.95843071],
       [ 0.98238451,  0.52221654,  0.75277142,  0.9239605 ,  0.16104512]])

In [10]:
X.shape

(3, 5)

In [11]:
np.sum(X, axis=1) # 1...columns

array([ 1.37085664,  3.74904757,  3.34237809])

In [ ]:
np.max(X, axis=0) # 0...rows

array([ 0.98238451,  0.96146941,  0.75277142,  0.9239605 ,  0.95843071])

## A quick-ish introduction to Pandas

based on http://pandas.pydata.org/pandas-docs/stable/10min.html

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#use a standard dataset of heterogenous data
cars = pd.read_csv('data/mtcars.csv')
cars.head()

In [ ]:
#list all columns
cars.columns

In [ ]:
#we want to use the car as the "primary key" of a row
cars.index = cars.pop('car')
cars.head()

In [ ]:
#describe our dataset
cars.describe()

In [ ]:
cars.sort_index(inplace=True)
cars.head()

In [ ]:
cars.sort_values('mpg').head(15)

In [ ]:
cars.sort_values('hp', ascending=False).head()

## Selection

**Note**: While many of the NumPy accessor methods work on DataFrames, you can also use the optimized pandas-specific data accessor methods, `.at`, `.iat`, `.loc`, `.iloc` and `.ix`.

See the [Indexing section](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing) and below.

In [ ]:
#single column
cars['mpg']

In [ ]:
#or a slice of rows
cars[2:5]

In [ ]:
#by label = primary key
cars.loc['Fiat 128':'Lotus Europa']

In [ ]:
#selection by position
cars.iloc[3]

In [ ]:
cars.iloc[3:5, 0:2]

In [ ]:
cars[cars.cyl > 6] # more than 6 cylinders

## Missing data

In [ ]:
cars_na = pd.read_csv('data/mtcars_with_nas.csv')

In [ ]:
cars_na.isnull().head(4)

In [ ]:
#fill with a default value
cars_na.fillna(0).head(4)

In [ ]:
#or drop the rows

print(cars_na.shape)
#drop rows with na values
print(cars_na.dropna().shape)
#drop columns with na values
print(cars_na.dropna(axis=1).shape)

#see also http://pandas.pydata.org/pandas-docs/stable/missing_data.html

## Statistics

In addition to `.describe()` there are plenty of other staticial measures and aggregation methods in Pandas/Numpy.

In [ ]:
#stats
cars.mean()

In [ ]:
cars.mean(axis=1)

In [ ]:
#grouping
cars.groupby('cyl').mean()

In [ ]:
#grouping different aggregation methods
cars.groupby('cyl').agg({ 'mpg': 'mean', 'qsec': 'min'})

## TASKS

In [ ]:
#loading gapminder data (taken from https://github.com/jennybc/gapminder)
#file located at 'data/gapminder-unfiltered.tsv' it uses tabular character as separator
#use the first column as index

In [ ]:
#what are the columns of this dataset?

In [ ]:
#what is the maximal year contained?

In [ ]:
#just select all data of the year 2007

In [ ]:
#locate Austria and print it

In [ ]:
#list the top 10 countries by life expectancy (lifeExp)

In [ ]:
#what is the total population (pop) per continent

## Next

[(Interactive) Plotting using Matplotlib and Seaborn](03_Plotting.ipynb)